---
title: "Tables for the manuscript"
author: "Piotr Prostko"
date: "14/12/2020"
output: pdf_document
classoption: notitlepage
header-includes:
  \AtBeginDocument{\let\maketitle\relax}
  \renewcommand{\thetable}{S\arabic{table}}  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,  message=FALSE,
  warning=FALSE)
```

```{r,echo=FALSE}
library(tidyverse)
library(kableExtra)
library(stringi)
source('manuscript_functions.R')
out_path <-'G:/My Drive/Isobaric labeling strategies/analyses output/' 
referenceCondition <- '0.5'
reportContrast <- '0.125'
# specify colours corresponding to biological conditions
condition.color <- tribble(
  ~Condition, ~Color,
  "0.125", 'black',
  "0.5", 'blue',
  "0.667", 'green',
  "1", 'red' )
data.list <- readRDS('input_data.rds')
dat.l <- data.list$dat.l 
spiked.proteins <- dat.l %>% distinct(Protein) %>% filter(stri_detect(Protein, fixed='ups')) %>% pull %>% as.character
sample.info <- get_sample_info(dat.l, condition.color)
channelNames <- remove_factors(unique(sample.info$Channel))
keep_objects=c('referenceCondition', 'reportContrast', 'condition.color', 'spiked.proteins','sample.info', 'channelNames', 'out_path','op','keep_objects')
```

```{r}
### Unit ###
# MODEL-BASED
rm(list = ls()[!(ls() %in% keep_objects)])
source('manuscript_functions.R')
load('modelbased_unit_outdata.rda')
dea.info <- get_dea_info(dat.dea)
cm <- conf_mat(dat.dea, 'q.mod', 0.05, spiked.proteins)
print_conf_mat(cm, '0.125', cap='Confusion matrix of the Unit component (Model-based approach). Due to a technical issue with fitting LMM, one protein is missing in the analysis of log intensities.', scale_font=999)

# DATA-DRIVEN
rm(list = ls()[!(ls() %in% keep_objects)])
source('manuscript_functions.R')
load('datadriven_unit_outdata.rda')
dea.info <- get_dea_info(dat.dea)
cm <- conf_mat(dat.dea, 'q.mod', 0.05, spiked.proteins)
print_conf_mat(cm, '0.125', cap='Confusion matrix of the Unit component (Data-driven approach).')

### Summarization ###
# MODEL-BASED
rm(list = ls()[!(ls() %in% keep_objects)])
source('manuscript_functions.R')
load('modelbased_summarization_outdata.rda')
dea.info <- get_dea_info(dat.dea)
cm <- conf_mat(dat.dea, 'q.mod', 0.05, spiked.proteins)
print_conf_mat(cm, '0.125', cap='Confusion matrix of the Summarization component (Model-based approach).')

# DATA-DRIVEN
rm(list = ls()[!(ls() %in% keep_objects)])
source('manuscript_functions.R')
load('datadriven_summarization_outdata.rda')
dea.info <- get_dea_info(dat.dea)
cm <- conf_mat(dat.dea, 'q.mod', 0.05, spiked.proteins)
print_conf_mat(cm, '0.125', cap='Confusion matrix of the Summarization component (Data-driven approach).')

### Normalization ###
# MODEL-BASED
rm(list = ls()[!(ls() %in% keep_objects)])
source('manuscript_functions.R')
load('modelbased_normalization_outdata.rda')
dea.info <- get_dea_info(dat.dea)
cm <- conf_mat(dat.dea, 'q.mod', 0.05, spiked.proteins)
print_conf_mat(cm, '0.125', cap='Confusion matrix of the Normalization component (Model-based approach).')

# DATA-DRIVEN
rm(list = ls()[!(ls() %in% keep_objects)])
source('manuscript_functions.R')
load('datadriven_normalization_outdata.rda')
names(dat.dea)[names(dat.dea)=='quantile'] <- 'quantile1'
names(dat.dea)[names(dat.dea)=='quantileByCondition'] <- 'quantile2'
dea.info <- get_dea_info(dat.dea)
cm <- conf_mat(dat.dea, 'q.mod', 0.05, spiked.proteins)
print_conf_mat(cm, '0.125', cap='Confusion matrix of the Normalization component (Data-driven approach).', scale_font=999)

### DEA ###
# MODEL-BASED
rm(list = ls()[!(ls() %in% keep_objects)])
source('manuscript_functions.R')
load('modelbased_DEA_outdata.rda')
dea.info <- get_dea_info(dat.dea)
cm <- conf_mat(dat.dea, 'q.mod', 0.05, spiked.proteins)
print_conf_mat(cm, '0.125', cap='Confusion matrix of the DEA component (Model-based approach).')

# DATA-DRIVEN
rm(list = ls()[!(ls() %in% keep_objects)])
source('manuscript_functions.R')
load('datadriven_DEA_outdata.rda')
dea.info <- get_dea_info(dat.dea)
cm <- conf_mat(dat.dea, 'q.mod', 0.05, spiked.proteins)
print_conf_mat(cm, '0.125', cap='Confusion matrix of the DEA component (Data-driven approach).')
```
