library(pacman)
library(rmarkdown)

# use this function before knitting each notebook to 'unload' packages (except base R packages)
unload_pkgs <- function() p_unload(setdiff(p_loaded(),c("pacman","rmarkdown")), character.only = TRUE)#

# function for automated knitting of a single notebook 
# name: character; the name of the notebook to be knitted (without .Rmd extension)
# input_data: character; the name of .Rds file generated by 'data_prep_XXX.R' script
# suffix: character; suffix used in notebook output file (html and rda) names
# load_outputdata:
#   subsample: numeric; 0 means all proteins, e.g. 50 means that 50 proteins will be randomly sampled.
#   subsample should be an integer >=0; if a very small number is specified, some errors may occurs (e.g. in normalization or DEA)

knit_notebook <- function(name, input_data, suffix='', load_outputdata=FALSE, subsample=0, norm_channels=''){
  notebook.params=list(input_data_p=input_data, suffix_p=suffix, load_outputdata_p=load_outputdata, subsample_p=subsample, norm_channels_p=norm_channels)
  if (suffix=='') tmp=name else tmp=paste0(name, '_', suffix)
  render(input = paste0(name,".Rmd"), 
         output_file = file.path(dirname(paste0(name,".Rmd")), tmp),
         params=notebook.params)
}

# first you need to run 'data_prep_XXX.R' script to process your raw data and save the resulting data
# as 'input_data_XXX.Rds' used in knitting the notebooks
# source('data_prep_msstatstmt.R')

# knit all the notebooks specified below
rm(list=setdiff(ls(),c('unload_pkgs', 'knit_notebook'))); unload_pkgs(); 
knit_notebook('intro', input_data='input_data_msstatstmt.Rds')

#### data-driven notebooks ####
rm(list=setdiff(ls(),c('unload_pkgs', 'knit_notebook'))); unload_pkgs(); 
knit_notebook("datadriven_unit", input_data='input_data_msstatstmt.Rds', suffix='msstatstmt', subsample=0, norm_channels='Norm') 

rm(list=setdiff(ls(),c('unload_pkgs', 'knit_notebook'))); unload_pkgs(); 
knit_notebook("datadriven_summarization", input_data='input_data_msstatstmt.Rds', suffix='msstatstmt', subsample=0, norm_channels='Norm') 

rm(list=setdiff(ls(),c('unload_pkgs', 'knit_notebook'))); unload_pkgs(); 
knit_notebook("datadriven_normalization", input_data='input_data_msstatstmt.Rds', suffix='msstatstmt', subsample=0, norm_channels='Norm') 

rm(list=setdiff(ls(),c('unload_pkgs', 'knit_notebook'))); unload_pkgs(); 
knit_notebook("datadriven_DEA", input_data='input_data_msstatstmt.Rds', suffix='msstatstmt', subsample=0, norm_channels='Norm') 

#### model-based notebooks ####
rm(list=setdiff(ls(),c('unload_pkgs', 'knit_notebook'))); unload_pkgs(); 
knit_notebook("modelbased_unit", input_data='input_data_msstatstmt.Rds', suffix='msstatstmt', subsample=0, norm_channels='Norm')  

rm(list=setdiff(ls(),c('unload_pkgs', 'knit_notebook'))); unload_pkgs(); 
knit_notebook("modelbased_summarization", input_data='input_data_msstatstmt.Rds', suffix='msstatstmt', subsample=0, norm_channels='Norm')  

rm(list=setdiff(ls(),c('unload_pkgs', 'knit_notebook'))); unload_pkgs(); 
knit_notebook("modelbased_normalization", input_data='input_data_msstatstmt.Rds', suffix='msstatstmt', subsample=0, norm_channels='Norm')   

rm(list=setdiff(ls(),c('unload_pkgs', 'knit_notebook'))); unload_pkgs(); 
knit_notebook("modelbased_DEA", input_data='input_data_msstatstmt.Rds', suffix='msstatstmt', subsample=0, norm_channels='Norm')  

#### other notebooks ####
rm(list=setdiff(ls(),c('unload_pkgs', 'knit_notebook'))); unload_pkgs(); 
knit_notebook("compare_defaults", input_data='input_data_msstatstmt.Rds', suffix='msstatstmt', subsample=0, norm_channels='Norm')  

rm(list=setdiff(ls(),c('unload_pkgs', 'knit_notebook'))); unload_pkgs(); 
knit_notebook("CONSTANd_vs_medianSweeping", input_data='input_data_msstatstmt.Rds', suffix='msstatstmt', subsample=0, norm_channels='Norm')   

rm(list=setdiff(ls(),c('unload_pkgs', 'knit_notebook'))); unload_pkgs(); 
knit_notebook("datadriven_unit_rawratio", input_data='input_data_msstatstmt.Rds', suffix='msstatstmt', subsample=0, norm_channels='Norm')  
 